[project]
name = "findmyfiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.6.3",
    "chroma>=0.2.0",
    "chromadb>=1.5.9",
    "fastapi[standard]>=0.139.0",
    "faster-whisper>=1.2.1",
    "gradio>=6.22.0",
    "langchain-text-splitters>=1.1.2",
    "openai>=2.52.1",
    "pymupdf>=1.28.2",
    "rapidocr-onnxruntime>=1.4.4",
    "redis>=8.0.1",
    "sqlmodel>=0.0.39",
]

[tool.fastapi]
entrypoint = "backend.app:app"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "requests>=2.34.2",
    "ruff>=0.15.21",
    "taskipy>=1.14.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"

[tool.uv]
config-settings = { "compile-bytecode" = "false" }

[tool.ruff.lint]
# Add "B" alongside your current active rules
select = ["F", "B"]

[tool.taskipy.tasks]
# Define your "dev" script shortcut here
lint = "ruff check ."
format = "ruff format ."
test = "pytest tests/"
dev = "uvicorn backend.app:app --reload   "
clean = "python -c \"import shutil; [shutil.rmtree(p, ignore_errors=True) for p in ['.pytest_cache', '__pycache__', '.ruff_cache','data'] ]\""
